spring:
  profiles:
   active: #init
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
          order_inserts: true
        generate_statistics: true